---
title: "每週一圖20191023"
output: html_document
params:
  組員: ["鄭喬翊"]  
  學號: ["410773098"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace);
library(rvest);library(XML);library(xml2)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
#install.packages(c("rvest","XML","xml2"))

library(dplyr); library(rvest); library(stringr)
source("https://www.dropbox.com/s/4tubw8e5h3cem6w/theEconomist.R?dl=1")

"https://www.economist.com/the-world-this-week/2019/11/21/politics-this-week" %>%
  get_theWorldThisWeek() -> df_politics

"https://www.economist.com/the-world-this-week/2019/11/21/business-this-week" %>%
  get_theWorldThisWeek() -> df_business

# save(<所有在graph_story.Rmd要用的物件列出來，中間用逗號分隔>, file="graphData.Rda") # 此行放在最後一行
```


```{r}
graphData <-list()

Country <-c("Sri Lanka",
        "Honkong",
        "US",
        "South Korea",
        "US",
        "Afghanistan",
        "US",
        "Iran",
        "Israel",
        "US",
        "Syria",
        "Burkina Faso",
        "Mali",
        "Niger",
        "Brazil",
        "Chile",
        "Bolivia",
        "Britain",
        "Sweden",
        "Belarus")

Event <- c("Election",
"Defiance",
"Law",
"Diplomatic",
"Diplomatic",
"Law",
"Election",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Defiance",
"Environment",
"Environment",
"Environment",
"Environment",
"Environment",
"Environment"
)

Continent <-c("Asia",
              "Asia",
              "America",
              "Asia",
              "America",
              "Asia",
              "America",
              "Asia",
              "Asia",
              "America",
              "Asia",
              "Africa",
              "Africa",
              "Africa",
              "America",
              "America",
              "America",
              "Europe",
              "Europe",
              "Europe"
)

politics <- data.frame(Country,Event,Continent)
```


```{r}

#choose_palette(gui="shiny")
colorspace::diverging_hcl(n = 5, h = c(255, 265), c = c(134, 104), l = c(36, 49), power = c(0.85, 0.85), register = "Custom-Palette") 

politics -> graphData$politicsCategory

graphData$politicsCategory %>%
  ggplot()+
  geom_point( aes(
    x = Event,
    y = Country,
    size = 15,
    color = Event,
  ),shape = 18)+
  scale_color_discrete_diverging(palette = "Custom-Palette")+
  labs(title = "Event Category",
       caption = "Source: The Economist"
       )+
  theme(plot.title = element_text(color = "#002F70",face = "bold",size = 20),
        plot.caption = element_text(color = "#002F70"),
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_rect(fill = 	"#DEFFFF"),
        axis.line = element_line(colour = "#002F70"),
        axis.ticks = element_line(colour = "#002F70"),
        axis.text = element_text(colour = "#002F70")
        ) -> graphData$politicsCategory_graph

graphData$politicsCategory_graph +
  facet_grid(Continent~. , scales = "free_y",space = "free_y") -> facet
facet #->graphData$EventCategory
 
#save(graphData,file = "EventCategory.Rda")
```

