---
title: "每週一圖20191023"
output: html_document
params:
  組員: ["鄭喬翊"]  
  學號: ["410773098"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework2/graphData_homework2_025.Rda?raw=true")) 

names(graphData$traffic) %>% # 檢查travelerFromAsia dataframe欄位名稱
tmcn::toUTF8() -> names(graphData$traffic) # 正確轉成utf8 存回原欄位名稱

graphData$traffic %>%
  mutate(
    自強號 = 自強號-自強號[1],
    莒光號 = 莒光號-莒光號[1],
    區間列車 = 區間列車 - 區間列車[1],
    高鐵 = 高鐵 - 高鐵[1]
  ) ->graphData$traffic
graphData$traffic <-graphData$traffic[c("年別","區間列車","高鐵","自強號","莒光號")]

save(graphData,file = "graphData.Rda")

# save(<所有在graph_story.Rmd要用的物件列出來，中間用逗號分隔>, file="graphData.Rda") # 此行放在最後一行
```

