---
title: "每週一圖20191023"
output: html_document
params:
  組員: ["鄭喬翊"]  
  學號: ["410773098"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


#### 繪圖程式

```{r graph, echo=T, eval=T}
load("graphData.Rda") # 此行為第一行

colorspace::sequential_hcl(n = 7, h = c(140, 138), c = c(50, NA, 62), l = c(20, 86), power = c(0.7, 1.8), register = "Custom-Palette")

library(reshape2)
graphData$traffic %>%
  melt(id.vars="年別") %>%
    ggplot(aes(x=年別,
               y=value)) + 
    geom_line(aes(color=variable),size=1.2
            ) +
  geom_vline(aes(xintercept=2015),size = 0.01,color="orange")+
  geom_hline(aes(yintercept=0),linetype="twodash",size = 0.05,color="gray") +
  scale_color_discrete_sequential(palette = "Custom-Palette",guide=guide_legend("運輸工具"))+
  labs(title = "2012-2017大眾運輸工具載客變化",
       subtitle="(以2012為基期)",
       x = "年份",y = "載客量")+
  theme(plot.background = element_rect(fill = "#9B4322"),
        panel.background = element_rect(fill = "#9B4322"),
        axis.ticks.x = element_line(color = "white"),
        axis.ticks.y = element_line(color = "white"),
        axis.text.x = element_text(color = "white"),
        axis.text.y = element_text(color = "white"),
        axis.title.x = element_text(color = "white"),
        axis.title.y = element_text(color = "white"),
        axis.line = element_line(color = "white"),
        plot.title = element_text(color = "white",face = "bold"),
        plot.subtitle = element_text(color = "white"),
        legend.background = element_rect(fill = "#9B4322"),
        legend.text=element_text(colour="white"),
        legend.title = element_text(color = "white"))
```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。

*** 
根據原作者的想傳達的訊息，主要是強調從2012-2017年各大眾交通運輸工具的載客量變化。因此我在此將其改成變化量，並以2012年為基期。
在區間列車方面，載客量年年上升，根據原作者判斷是由於對短程交通的需求升高。
根據原作者的訊息，在2015-2016高鐵苗栗、彰化、雲林站的開通，使高鐵載客量有明顯的上升。而莒光號基本上在2013年之後不斷呈現負成長，自強號也在2015年後載客量有下降趨勢。

