---
title: "Untitled"
author: "Joey"
date: "2019年11月13日"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr);
library(tidyr); library(showtext);library(sf)

font_add("QYuan","C:/Users/user/Desktop/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
point <- st_point(
  c(2,3)
)

point %>% ggplot()+geom_sf()
```
## 多點，需用rbind()矩陣
```{r}
mpoint <- st_multipoint(
    rbind(c(1,0),
        c(2,3),
        c(-1,2))
)

mpoint %>% ggplot()+geom_sf()
```

#單條線，由多點形成
```{r}
line <- st_linestring(
    rbind(c(1,0),
        c(2,3),
        c(-1,2))
)
line %>% ggplot()+geom_sf()
```

#多條線，需用多個矩陣，再用list合成一張圖
```{r}
mline <- st_multilinestring(
  list(
    rbind(
      c(1,0),
      c(2,3),
      c(-1,3)),
    
    rbind(
      c(-2,3),
      c(-1,-1))
    )
  )

mline %>% ggplot()+geom_sf()
```

#面，第一個自動視為最外圍，剩下皆是hole
```{r}
outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it
  
poly <- st_polygon(
  list(
    outer,  #外圍
    hole    #hole
  )
) 

poly %>% ggplot()+geom_sf()
```

#多個面
```{r}
outer2 <- outer + 12
hole2 <- hole + 12

mpoly <- st_multipolygon(
  list(
    list(
      outer,
      hole
    ),         #一個list即一個面
    list(
      outer2,
      hole2
    )
  )
) 

mpoly %>% ggplot()+geom_sf()
```

##st_geometrycollection() 全部集中在同一張圖上
```{r}
st_geometrycollection(
  list(
    point, mpoint,
    line, mline,
    poly, mpoly
  )
) %>% ggplot()+ geom_sf()
```

```{r}
#架構每個county的sf geometry
sfg_county1 <- st_polygon(list(
  outer,hole
))

sfg_county2 <- st_polygon(list(
  outer2, hole2
))



sfc_county12column <- st_sfc(sfg_county1,sfg_county2) #single feature column

sfc_county12column %>% ggplot+geom_sf()
```

```{r}
df_county12 <- data.frame(
  name=c("county1","county2"),
  population=c(100,107)
)

df_county12 %>%
  st_set_geometry(sfc_county12column) -> df_county12

df_county12 %>% names
```


```{r}
class(df_county12)

df_county12
```

```{r}
df_county12 %>%
  ggplot() + geom_sf(
    aes(fill=population)
  ) +
  geom_sf_text(
    aes(label=name)
  )
```


```{r}
sfc_county12column %>%
  st_set_crs(4326) -> # EPSG: 4326
  sfc_county12column
```

```{r}
dir.create("county12")
write_sf(df_county12,"county12/county12.shp") #檔名/檔案類型
```


#practice
```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```


```{r}
sf_mrt_tpe %>%
  filter(
    stringr::str_detect(經過路線,"BL")
  ) -> sf_mrt_tpe_bl
```


```{r}
sf_mrt_tpe_bl %>%
  st_coordinates()  %>%
  st_linestring() -> sfg_mrt_bl
```

```{r}
sfg_mrt_bl %>%
  ggplot()+geom_sf()
```


```{r}
sf_mrt_tpe_bl %>%
  mutate(
    站號 = stringr::str_extract(
      經過路線,"(?<=(BL))[:digit:]+"   #找出屬於BL字眼之後的數字，使data照順序
    )
  ) %>%
  arrange(站號)-> sf_mrt_tpe_bl
```

#繪製板南線
```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_bl  #捷運板南線的simple feature geometry

sfg_mrt_bl %>%
  ggplot()+geom_sf()
```


```{r}
df_mrt <- data.frame(
  linename="BL"
)
sfg_mrt_bl %>%
  st_sfc() -> sfc_mrt_bl
df_mrt %>%
  st_set_geometry(sfc_mrt_bl) -> 
  df_mrt
df_mrt
```

```{r}
sf_mrt_tpe %>%
  st_crs -> mrt_crs
df_mrt %>%
  st_set_crs(mrt_crs) ->
  df_mrt
df_mrt
```

#homework 中和新蘆線
```{r}
sf_mrtStops_tpe %>%
  filter(
    stringr::str_detect(經過路線,"O")
  ) -> sf_mrt_tpe_o

sf_mrt_tpe_o %>%
  mutate(
    站號 = stringr::str_extract(
      經過路線,"(?<=(O))[:digit:]+"   #找出屬於O字眼之後的數字，使data照順序
    )
  ) %>%
  arrange(站號)-> sf_mrt_tpe_o
```


```{r}
sf_mrt_tpe_o %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_o



sfg_mrt_o_final <- st_multilinestring(
  list(
    rbind(
      c(1,0),
      c(2,3),
      c(-1,3)),
    
    rbind(
      c(-2,3),
      c(-1,-1))
    )
  )

mline %>% ggplot()+geom_sf()
```



```{r}
Taiwan <- read_sf("C:/Users/user/Documents/GitHub/secondpractice310/course-108-1-inclass-datavisualization/mapdata201907311006")
```

```{r}
Taiwan %>%
  ggplot() + geom_sf()
```

