---
title: "Untitled"
author: "Joey"
date: "2019-09-25"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr);
library(tidyr); library(showtext)

font_add("QYuan","C:/Users/user/Desktop/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r cars}
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)
```


```{r cars}
df_gatherExample
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口") #gather中的變數選擇可使用select helper
```



```{r pressure, echo=FALSE}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```


```{r pressure, echo=FALSE}
gather(collegeData,
       contains("生"),key = "類別",value = "人數") ->collegeDataGather
```


```{r pressure, echo=FALSE}
library(readr)
```

```{r pressure, echo=FALSE}
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")
```

```{r}
df_taoyuanMarriage %>%
gather(
  -月份區域別, #endswith()
       key = "月份" ,value = "對數") ->df_taoyuanMarriageGather

```

#每個月桃園總結婚對數
```{r}
df_taoyuanMarriageGather %>%
  group_by(月份) %>%
  summarise(總結婚對數 = sum(對數)) ->df_taoyuanMarriageGatherSum
```

#每個地區結婚最高峰月份!!!!
```{r}
df_taoyuanMarriageGather %>%
  group_by(月份區域別) %>%
  summarise(最高峰月份 = 月份[[which.max(對數)]]) ->df_taoyuanMarriageGather_max
```


```{r}
df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朶萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))
```

```{r}
df_spreadExample
spread(df_spreadExample,
       var,value) %>% View
```

```{r}
collegeDataGather %>%
  spread(
    類別,人數
  )
```

```{r}
df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")
```
```{r}
df_twbankExchangeRate %>%
  select(-即期賣出匯率) %>%
  spread(
    幣別,即期買入匯率
  ) ->df_twbankExchangeRate_spread
```

#變數類別調整
```{r}
df_twbankExchangeRate %>%
  mutate(即期買入匯率 = as.numeric(即期買入匯率),
  幣別 = as.factor(幣別),
  即期賣出匯率 = as.numeric(即期賣出匯率),
  日期 = lubridate::ymd(日期)) ->df_twbankExchangeRate
```

```{r}
library(readr); library(dplyr)
# 線上引入原始資料成字串向量
read_lines("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates") ->
  originalLines

# 將字串由CP950編碼改成UTF8再讀成data frame data2
originalLines %>%
  iconv(from="CP950",to="UTF8") %>% 
  read_csv() -> data2
```


```{r}
library(lubridate)
taifex_open_data %>%
  mutate(日期 = ymd(日期)) -> taifex_open_data
```

#資料引入!!
```{r}
library(readr)
read_lines("
http://data.cec.gov.tw/選舉資料庫/voteDate.csv") ->governmentData
```

```{r}
library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")
```

```{r}
library(lubridate)
subsetDataTWbank %>%
  ym(年月) ->subsetDataTWbank
```
```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```
```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```

#pipe
```{r}
subsetDataTWbank %>%
  ggplot() +
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```

```{r}
subsetDataTWbank %>%
  gather(contains("定存利率"),key = "定存類型" , value = "利率") ->subsetDataTWbank_gather 
subsetDataTWbank_gather %>%  
  ggplot()+
  geom_boxplot(aes(x = 定存類型 , y = 利率))
#boxplot 看資料的離散程度(四分位差)
#點代表outlier(極端值)
```

```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```

#可以直接疊加(inherit)
```{r}
library(ggplot2)
ggplot(subsetDataTWbank,
       aes(x=西元年月,y=`定存利率-一個月-固定`))+
  geom_line()+
  geom_point()
```

```{r}
subsetDataTWbank_gather %>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=利率,color=定存類型)
  ) #必須先gather才有辦法畫3條線，因X軸為"定存類型"
```

```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`),
    color="red",
    alpha = 1,  #透明度，1完全不透明、0完全透明
    size = 2  #必跟著連續變數
  )
```

##字串變數
```{r}
subsetDataTWbank_gather$定存類型 %>% 
  as.factor %>% levels
```

```{r}
subsetDataTWbank_gather %>%
  mutate(
    定存類型=factor(定存類型,levels=c("定存利率-一個月-固定","定存利率-二年期-固定","定存利率-三年期-固定")) #打出的順序即為資料順序
  ) -> subsetDataTWbank_gather

#重新製圖
subsetDataTWbank_gather %>%
  ggplot()+
  geom_boxplot(aes(x=定存類型,y=利率))
```





```{r}
twCalendar <- c("民國88年11月1日","民國88年12月1日","民國89年1月1日")
```



```{r}
twCalendar %>%
  # 取出字串中的數字部份
  stringr::str_extract_all("[:digit:]+") %>%
  # 將每個日期的「年」數字加上1911再合併年月日成為`yyyy-mm-dd`格式
  purrr::map_chr(
             function(x) {
               x1=as.integer(x[[1]])+1911
               x[[1]]=as.character(x1)
               stringr::str_c(x,collapse="-")
             }
             ) -> westernCalendar
```


```{r}
westernCalendar %>%
  lubridate::ymd() -> datetimeCalendar
class(datetimeCalendar)
```

```{r}
subsetDataTWbank %>%
  mutate(
    年月=年月 %>%
      stringr::str_extract_all("[:digit:]+") %>% #取出數字部分，因有"/"
      purrr::map_chr(
                 function(x) {
                   x1=as.integer(x[[1]])+1911
                   x[[1]]=as.character(x1)
                                stringr::str_c(x,collapse="-")
                 }
                 ),
    年月日=stringr::str_c(年月,"01",sep="-"), #加上01日期
    西元年月日=lubridate::ymd(年月日) #轉為時間class
  ) ->subsetDataTWbank


```

