---
title: "Untitled"
author: "fish"
date: "2019年9月11日"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr);
library(tidyr); library(showtext)

font_add("QYuan","C:/Users/user/Desktop/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)

```

```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF 
```

```{r}
class(StuDF) #當作data frame做變化
typeof(StuDF) #儲存為list

class(StuList) #只可作為list做變化
```

```{r}
length(StuDF) # 從向量角度看 長度
nrow(StuDF) # 從矩陣角度看

ncol(StuDF) #可用length()替代
```

```{r}
library(dplyr);library(tidyr);library(lubridate);library(stringr)

str(StuDF)

head(StuDF) #檢查前6項

tail(StuDF) #檢查後6項

```

```{r}
#依row位置選擇資料
StuDF
slice(StuDF,1:3)
slice(StuDF,4:5)
slice(StuDF,n())

slice(StuDF,(n()-1):n()) #倒數
slice(StuDF,7:8)

StuDF
slice(StuDF,-5:-7) #5,6,7不要
slice(StuDF,-(5:7))#5,6,7不要
```

```{r}

```


