---
title: "Untitled"
author: "Joey"
date: "2019年9月11日"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr);
library(tidyr); library(showtext)

font_add("QYuan","C:/Users/user/Desktop/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
```
```{r}
library(grDevices)
rgb(0,0,1) # 即對應顏色強度(0,0,255)
```




```{r cars}
rgb(0.5,0,0.7) # 即對應顏色強度(0.5*255,0,0.7*255)進位到整數
```


```{r pressure, echo=FALSE}
library(scales)
show_col(c(rgb(0,0,1),rgb(0.5,0.5,0.1)))
```



```{r}
show_col(
  c(
    hsv(30/360,0,0),hsv(30/360,0.5,0),hsv(30/360,1,0), # (,,lightness=0) 全暗
    hsv(30/360,0,0.5),hsv(30/360,0.5,0.5),hsv(30/360,1,0.5), # (,,lightness=0.5)
    hsv(30/360,0,1),hsv(30/360,0.5,1),hsv(30/360,1,1) # (,,lightness=1) 全亮
  )
```


```{r}
choose_color(
)
show_col("#A78D5F")
```



```{r}
choose_palette(gui="shiny")
```


```{r}

```
```{r}
data.frame(
  x1 = factor(sample(c(1L,2L,3L),100,replace=T)),
  x2 = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = factor(sample(letters[1:4],100,replace=T))
) -> df_example
```

```{r}
df_example %>%
  ggplot()+
  geom_boxplot(
    aes(x=x1,y=y,fill=z2)
  ) -> basicBoxplot
basicBoxplot
```
```{r}
colorspace::sequential_hcl(n = 9, h = 270, c = c(70, NA, NA), l = c(25, 95), power = 1, register = "Custom-Palette") ->color1
color1
```

```{r}
colorspace::diverging_hcl(n = 7, h = c(260, 0), c = 80, l = c(30, 90), power = 1.5, register = "Custom-Palette") ->color2

basicBoxplot +
  scale_fill_discrete_qualitative(palette="color2",nmax=5)
```


```{r}
#由於色圈會由0度出發回到360度所以第1個及第5個會是同色，因此4類要創出5個顏色才不會有1,4類同色問題。
```

```{r}
df_example %>%
  ggplot()+
  geom_point(
    aes(x=x2,y=y,color=z1)
  ) -> basicScatterPlot
```





```{r}
basicScatterPlot +
  scale_color_continuous_sequential(palette = "color1")
```

```{r}
basicScatterPlot+ 
 scale_color_distiller(palette="RdGy")
```

```{r}
basicBoxplot+
  scale_fill_brewer(type="seq" , palette = "RdPu")
```

