---
title: "Untitled"
author: "Joey"
date: "2019年10月23日"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr);
library(tidyr); library(showtext);library(sf)

source("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1")

font_add("QYuan","C:/Users/user/Desktop/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)


```


# Introduction 

In this example, two sf's (sf_northTaiwan and sf_mrtStops_tpe) have different CRS's. 

  * Set them to the same CRS before you graph them together. 

# MRT BL stops

```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```

## Retrieve BL stops from all Taipei MRT

```{r}
sf_mrtStops_tpe %>%
  filter(
    str_detect(經過路線,"BL")
  ) %>%
  mutate(
      站號=str_extract(經過路線,"(?<=(BL))[:digit:]+")
            ) %>%
  arrange(站號) -> sf_mrtStops_tpe_BL
```




```{r}
graph <- list()
sf_mrtStops_tpe_BL %>%
  ggplot()+geom_sf() -> graph$mrt_BL_stops
graph$mrt_BL_stops
```

```{r}
sf_mrtStops_tpe_BL %>% st_bbox
sf_mrtStops_tpe_BL %>% st_crs
```


## graph north taiwan


```{r}
load(url("https://www.dropbox.com/s/elnvocol0nnkcc9/sf_northTaiwan.Rda?dl=1"))
sf_northTaiwan %>%
  rmapshaper::ms_simplify() -> sf_northTaiwan
sf_northTaiwan
```

```{r}
sf_northTaiwan %>% st_bbox()
sf_northTaiwan %>% st_crs()
```


```{r}
sf_northTaiwan %>% 
  ggplot()+geom_sf() -> graph$northTaiwan
graph$northTaiwan
```

# graph Both north taiwan and BL stops

## set consistent CRS before you start

```{r}
crs0 <- sf_northTaiwan %>% st_crs()
sf_mrtStops_tpe_BL %>%
  st_transform(crs=crs0) -> sf_mrtStops_tpe_BL  # if sf already has CRS, use st_transform
```


```{r}
st_geometry(sf_northTaiwan)
st_geometry(sf_mrtStops_tpe_BL)
```

## graph

```{r}
graph$northTaiwan +
  geom_sf(
    data=sf_mrtStops_tpe_BL
  ) -> graph$northTaiwan_with_BLstops
graph$northTaiwan_with_BLstops
```

# Make BL stops into BL line

## from points to linestring
```{r}
# forming a linestring sfc
sf_mrtStops_tpe_BL %>%
  st_geometry() %>%
  st_coordinates() %>% # you lose CRS at this step,class matrix
  st_linestring() %>%  #class sfg
  st_geometry() -> sfc_BL_line # only sfc can be assigned CRS
# ## Error: sfc object should have crs set
# graph$northTaiwan_with_BLstops +
#   geom_sf(
#     data=sfg_BL_line
# )
# assing CRS to sfc
sfc_BL_line %>% 
  st_set_crs(  ##原先沒有crs
    st_crs(sf_northTaiwan) ##使geometry column與northTaiwan一致
  ) -> sfc_BL_line
graph$northTaiwan_with_BLstops+
  geom_sf(
    data=sfc_BL_line
  ) -> graph$northTaiwan_with_BL
graph$northTaiwan_with_BL
```



```{r}
# just to show CRS again
sfc_BL_line %>% st_crs
sf_northTaiwan %>% st_crs
sf_mrtStops_tpe_BL %>% st_crs
```

## coord_sf

```{r}
graph$northTaiwan_with_BL+
  coord_sf(
    xlim=c(121.4,121.7),
    ylim=c(24.9,25.09)
  )
```


```{r}
library(osmdata)

st_read("map.osm") ->state

st_read("map.osm",layer = "lines") ->lines_state
```

```{r}
lines_state %>%
  ggplot()+geom_sf()
```


```{r}
st_read("map.osm",layer="points") ->point_state


point_state %>%
  ggplot() + geom_sf()
```


```{r}
st_read("map.osm",layer = "multipolygons") -> polygon_state

polygon_state %>%
  ggplot() + geom_sf()
```



```{r}
st_read("map1.osm") -> cloudgates
st_read("map1.osm",layer = "multipolygons") ->polygon_cloudgates
st_read("map1.osm",layer = "lines") -> line_cloudgates
st_read("map1.osm",layer = "points") ->point_cloudgates


polygon_cloudgates %>%
  ggplot() + geom_sf()+geom_sf(data = line_cloudgates) 


```

##bbox
```{r}
opq(bbox = c(121.42789,25.17949,121.43039,25.1808)) ->opq_state

opq_state %>%
  add_osm_feature(key = "tourism",value = "attraction") %>%
  osmdata_sf() ->map_state

map_state$osm_polygons %>%
  ggplot() + geom_sf() +
  geom_sf(data = map_state$osm_points)
```



```{r}
library(osmdata)
# open pass query with bounding box
bbox_taipei <- opq(
  bbox = c(121.4616,25.1050,121.6058,24.9894) 
) 
```


```{r}
bbox_taipei %>%
  add_osm_feature(
    key="admin_level", value="5"
  ) %>%
  osmdata_sf() -> map_taipei_boundary

map_taipei_boundary  
```

```{r}
map_taipei_boundary$osm_multipolygons -> map_taipei #class is sf
```

```{r}
map_taipei %>%
  ggplot() + geom_sf()
```


```{r}
source("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1")

download.file("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1",destfile = "data_visualization_pk_R")
```


```{r}
map_taipei %>%
  osm_geom_rename() %>%
  ggplot() + geom_sf()
```



```{r}
billionaire <- 
  read_csv("https://www.dropbox.com/s/cpu4f09x3j78wqi/billionaire.csv?dl=1") %>%
  rename(
    "Year"="X1"
  )
```


```{r}
billionaire %>%
  ggplot()+geom_line(
    aes(x=Year,y=Russia)
  ) +
  scale_y_continuous(
    breaks=seq(0,200,by=50)
  ) +
  theme_linedraw()-> plot_russia
plot_russia

billionaire %>%
  ggplot()+geom_line(
    aes(x=Year,y=World)
  )+
  scale_y_continuous(
    breaks=seq(0,2000,by=500)
  ) +
  theme_linedraw()-> plot_world
plot_world
```


```{r}
f <- function(x) x/10
f_inverse <- function(f_value) 10*f_value
```


```{r}
billionaire %>%
  mutate(
    World2=f(World)
  ) -> billionaire
```


```{r}
billionaire %>%
  ggplot()+
  geom_line(
    aes(x=Year,y=Russia), color="blue", size=2
  ) +
  geom_line(
    aes(x=Year,y=World2), color="brown", size=2
  ) + 
  scale_y_continuous(
    limits=c(-1,230),
    breaks=seq(0,200,by=50),
    expand=expand_scale(mult=c(0,0)), ##消除0在y軸上多出來的空格
    sec.axis = sec_axis(  # 設定右Y軸
      trans=f_inverse,
      name="Rest of the World"
    )
  ) +
  theme_bw() -> plot_sec_axis 

plot_sec_axis
```


```{r}
load(url("https://www.dropbox.com/s/r21jg0vxf77geu9/plot_tree.Rda?dl=1"))

plot_tree
```


```{r}
plot_tree +
  scale_x_continuous(
    sec.axis = dup_axis()
  ) 
```


```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework6/graphData_homework6_021.Rda?raw=true"))
source("https://www.dropbox.com/s/0ydtqtxu5guy6i1/theme_lin.R?dl=1")

resume_df %>% 
  mutate(開始 = ymd(開始), 結束 = ymd(結束))  -> resume_df
```

```{r}
resume_df %>%
  ggplot(
    aes(x = 開始, y = 項目)) +    
  geom_text(
    aes(label = 名稱), size = 2.5) + 
  geom_segment(
    aes(
      xend = 結束, yend = 項目, color = 分類, size = 2, alpha = 1
      )
    ) +
  scale_x_date(
      breaks = seq(as.Date("2015-01-01"), as.Date("2020-01-01"), by="1 year"),
      labels = scales::date_format("%Y")
      )+
  labs(title = "Kuo, Shih-Jung  郭士榮", subtitle = "熱愛挑戰不設限、豐富國際經驗、在學三份實習") + 
  theme_lin() -> gg_basic

gg_basic
```


```{r}
gg_basic +
  facet_grid(分類~.) -> gg_facet

gg_facet
```


```{r}
gg_basic +
  facet_grid(分類~.,  scales = "free_y") -> gg_facet_free

gg_facet_free
```


```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_002.Rda?raw=true"))

graphData$sub_2015_city%>%
  arrange(desc(area), avg_nh)%>%
  mutate(city = forcats::fct_inorder(city)) -> df_eldercare
```

```{r}
df_eldercare %>%
  ggplot(
    aes(y = avg_nh, x = city, fill = area)
    )+
  geom_col(
    width=0.7
  )+
  coord_flip()+
  labs(x = "長照機構數(每10,000位老人)", y="")+
  theme_lin() -> gg_original

gg_original
```

```{r}
gg_original+
  facet_grid(
    rows=vars(area), scales="free_y"
  )
```

```{r}
gg_original+
  facet_grid(
    rows=vars(area), scales="free_y", space="free_y"
  )
```

