---
title: "每周一圖20191225"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r basic setup, message=FALSE, echo=FALSE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)
library(utils)

font_add("QYuan","C:/Users/user/Desktop/cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


```{r}
poster <-read.csv("C:/Users/user/Desktop/poster.csv")
facebook <- read.csv("C:/Users/user/Desktop/facebook.csv")
website <- read.csv("C:/Users/user/Desktop/website.csv")
```

```{r}
rbind(poster,facebook,website) ->all
as.factor (all$hour) -> all$hour
#class(all$hour)

all %>%
  group_by(hour) %>%
  summarise(
    frequency = length(hour)
  ) ->summariseAll

summariseAll <- read.csv("C:/Users/user/Desktop/summariseAll.csv")
```

```{r}
#file.create(".Rprofile")
#file.edit(".Rprofile") 

#source(".Rprofile")
#Sys.getenv("plotly_username")
#Sys.getenv("plotly_api_key")
```


Column {.tabset data-width=600}
-------------------------------------
    
### Chart 1
    
```{r}
#choose_palette(gui="shiny")

summariseAll %>%
  ggplot(aes(x=hour,y=frequency))+
  geom_line(color = "#195EA3",size = 1)+#517AC9
  geom_point(color = "#003969",size = 3)+  
  labs(x = "時間",
       y = "次數",
       title = "各時間點擊次數",
       subtitle = "以小時為單位")+
  theme(
    plot.background = element_rect(fill  = "#C5E5FF"),
    panel.background = element_rect(fill = "#C5E5FF"),
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.title.y =element_blank(),
    axis.title.x =element_blank(),
    plot.title = element_text(color = "#003A91",size = 35,face = "bold"),
    plot.subtitle = element_text(color = "#003A91",size = 30),
    axis.ticks = element_blank(),
  ) ->clickNumber1

#clickNumber1

#api_create(clickNumber1,filename="clickNumber1",fileopt="overwrite") -> Meta_plotly_clickNumber

plotly_clickNumber <- api_download_plot("5","Chiaoyi")
plotly_clickNumber
```
   
Column  {.tabset data-width=400} 
-------------------------------------
   
### Chart 2

```{r}
#choose_palette(gui="shiny")

網站 <-c("臉書","海報","官網")
次數 <-c(62,52,71)

visitData <-data.frame(網站,次數)

visitData %>%
  ggplot(aes(x = 網站,y = 次數))+
  geom_col(fill = "#5ECBFD",size = 0.5)+
  geom_hline(yintercept = 0,color = "#00366C")+
  theme(
    axis.line.x  = element_blank(),
    axis.line.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.text.x  = element_blank(),
    plot.title = element_text(color = "#00366C",face = "bold",size = 50),
    axis.text = element_text(color = "#00366C",size = 35)
  )+
  geom_text(aes(label = 次數),position = position_stack(vjust = 0.95),size = 15,color = "#00366C")+
  coord_flip()+
  labs(title = "各網站觸及次數")
```   
 
### Chart 3
    
```{r}
#choose_palette(gui="shiny")
colorspace::sequential_hcl(n = 5, h = c(260, 247), c = c(56, 125, 117), l = c(29, 84), power = c(1.55, 0.6), register = "Custom-Palette")

all %>%
  group_by(event.title) %>%
  summarise(
    次數 = length(event.title)
  ) ->allSummarise


allSummarise %>%
  ggplot(aes(x = event.title,y = 0.5,color = 次數,size = 次數))+
  scale_color_continuous_sequential(palette = "Custom-Palette")+
  geom_point()+
  scale_size_area(
    max_size = 60
  )+
  scale_y_continuous(limits = c(0,1))+
  labs(title = "各活動觸及人數")+
  theme(
    legend.position = "none",
    axis.line = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    plot.title = element_text(size = 50,face = "bold")
  )+
 annotate("text",x = 1,y = 0.2,size = 10,
    label = paste("北大玩具節")
  )+
  annotate(
    "text",x = 2,y = 0.2,size = 10,
    label = paste("青銀共賞電影")
  )+
  annotate("text",x = 3,y = 0.2,size = 10,
           label = paste("聖誕點燈暨北大管樂節"))+
  geom_text(aes(label = 次數),position = position_stack(vjust = 0.97),size = 15,color = "white")
```
